name: Build, Validate, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-validate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x mvnw

      # 1 Code Validation (Linting, Formatting, Compile Checks)
      - name: Validate Code with Maven
        run: ./mvnw clean validate

      - name: Run Static Code Analysis (Checkstyle)
        run: ./mvnw checkstyle:check

      # 2 Vulnerability Scanning with SonarCloud
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.projectKey=sazhnov-perfromance_openVTS \
            -Dsonar.organization=sazhnov-performance \
            -Dsonar.host.url=https://sonarcloud.io

      # 4 Build JAR
      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      # 5 Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6 Build and Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sazhnovperformance/openvts:latest
